name: CI - Web Crawler
on:
  push:
    branches: dev

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26.2"
          cache: true

      - name: Test Web Crawler
        run: go test ./web-crawler -race

      - name: Lint Web Crawler
        run: go vet ./web-crawler

      - name: Build Web Crawler
        run: go build ./web-crawler
