name: CI - Key Value

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26.2"
          cache: true

      - name: Run Go Test
        run: go test -race ./kv/...

      - name: Run Go Lint
        run: go vet ./kv/...

      - name: Run Go Build
        run: |
          go build -o server ./kv/server
          go build -o client ./kv/client
